//
//  UXRGlobals.m
//
//  Created by Rex St. John on 12/20/13.
//  Copyright (c) 2013 UX-RX. All rights reserved.
//

#import "UXRGlobals.h"

@implementation UXRGlobals

const NSString* TESTFLIGHT_TOKEN = @"76b57683-4548-4a54-b5f4-1357023f4e90";

const NSString* LISTEN_REQUEST_NOTIFICATION = @"LISTEN_REQUEST_NOTIFICATION";
const NSString* REDEEM_REQUEST_NOTIFICATION = @"REDEEM_REQUEST_NOTIFICATION";
const NSString* REWATCH_REQUEST_NOTIFICATION = @"REWATCH_REQUEST_NOTIFICATION";
const NSString* USER_PROFILE_REQUEST_NOTIFICATION = @"USER_PROFILE_REQUEST_NOTIFICATION";

const NSString* WATCH_AD_SEGUE = @"WATCH_AD_SEGUE";
const NSString* REDEEM_SEGUE = @"REDEEM_SEGUE";
const NSString* LISTEN_SEGUE = @"LISTEN_SEGUE";
const NSString* AD_DETECTED_SEGUE = @"AD_DETECTED_SEGUE";
const NSString* USER_PROFILE_SEGUE = @"USER_PROFILE_SEGUE";

@end
